### ISSUE TITLE
Feature: ToDo and Complete Columns

### ISSUE THREAD

**Issue by Jorgan612** [Jorgan612/write-on#17]
On the Dashboard, there is a section to track items of importance:
- [ ] A To Do column to add the things you need to do to
- [ ] A completed column to move completed To Do items to
- [ ] States will update with a small section on completed tasks for a positive mood boost on how much progress a user has made toward their goals
- [ ] Items can be dynamically moved up and down to show the level of priority for each item
- [ ] To Dos and modifications to the lists deletes, additions, and reorders will persist on page refresh
